FROM node:20.15-alpine3.19

WORKDIR /app

COPY .gitignore .gitignore
COPY apps/web/package.json ./package.json
COPY apps/web/yarn.lock ./yarn.lock

RUN yarn install

COPY apps/web .

EXPOSE 3000

CMD ["yarn", "dev"]
